title: NUS SELAB
name: "NUS SELAB"
author: NUS SELAB
twitter_username: 
baseurl: ""
description: Document my learning notes.
profile_url: "http://nus-selab.github.io"

# Build settings
markdown: kramdown
highlighter: rouge
excerpt_separator: <!--more-->
plugins:
  - jekyll-feed
  - jekyll-archives
exclude:
  - Gemfile
  - Gemfile.lock
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
  toc_levels: 1..3
